Tutorial 1 Start-up
===

## What is PyTorch?

It's a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

In [1]:
import torch
print(torch.cuda.is_available())
# or equivalent use cmd command: nvcc -V, to check whether you have available GPU and its version

True


## Getting started
### Tensors
Tensors are similar to NumPy's ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.


#### 1. Construct an uninitiallized 5x3 matrix:

*NB Here creating uninitiallized matrix will only allocate location for the matrix, but will not assign values to the matrix. The matrix values will only display the value originally in that location.*

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


#### 2. Construct a randomly initialized matrix:

In [5]:
x = torch.rand(5,3)
print(x)

tensor([[0.9926, 0.3008, 0.8665],
        [0.1108, 0.9536, 0.4675],
        [0.2299, 0.4196, 0.4039],
        [0.8018, 0.7661, 0.2092],
        [0.7811, 0.9025, 0.3176]])


#### 3. Construct a all-zeros matrix and of dtype long:

In [6]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


#### 4. Construct a tensor directly from data:

In [7]:
x = torch.tensor([5.5,3])
# similar as np.array(.) in numpy
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user:

In [8]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.2506,  0.7718,  0.8466],
        [-0.3260, -1.1053, -0.6497],
        [ 0.3160, -0.1854, -0.2642],
        [-2.4903, -0.3183,  0.4290],
        [ 0.0026, -0.8582, -0.9284]])


Get a tensor's size with .size():

In [9]:
print(x.size())

torch.Size([5, 3])


In [15]:
a = x.size()[1]
# .size() returns a tuple and supports all tuple operations
a

3

### Tensor Operations

In [22]:
# 1. Addition
y = torch.rand(5,3)
print(x+y)
# with torch.add(.)
print(torch.add(x,y))
# return in a new space, but declare the new location for the new variable first
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)
# in-place
y.add_(x)
print(y)

tensor([[ 1.0409,  1.3185,  0.8736],
        [ 0.6078, -1.0152,  0.0228],
        [ 1.1518, -0.1721,  0.2281],
        [-1.8165,  0.1040,  1.2791],
        [ 0.3526, -0.3380, -0.1102]])
tensor([[ 1.0409,  1.3185,  0.8736],
        [ 0.6078, -1.0152,  0.0228],
        [ 1.1518, -0.1721,  0.2281],
        [-1.8165,  0.1040,  1.2791],
        [ 0.3526, -0.3380, -0.1102]])
tensor([[ 1.0409,  1.3185,  0.8736],
        [ 0.6078, -1.0152,  0.0228],
        [ 1.1518, -0.1721,  0.2281],
        [-1.8165,  0.1040,  1.2791],
        [ 0.3526, -0.3380, -0.1102]])
tensor([[ 1.0409,  1.3185,  0.8736],
        [ 0.6078, -1.0152,  0.0228],
        [ 1.1518, -0.1721,  0.2281],
        [-1.8165,  0.1040,  1.2791],
        [ 0.3526, -0.3380, -0.1102]])


*NB Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.*

In [26]:
# Resizing: If you want to resize/reshape tensor, you can use torch.view:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(y,z)
print(y.size(),z.size())

tensor([ 0.1979,  0.5036, -0.4211, -0.4818, -0.1331, -0.9256,  0.1336,  0.5035,
        -0.6307, -0.3582, -1.2519, -1.1975,  0.9288, -1.6118,  1.4143,  1.2810]) tensor([[ 0.1979,  0.5036, -0.4211, -0.4818, -0.1331, -0.9256,  0.1336,  0.5035],
        [-0.6307, -0.3582, -1.2519, -1.1975,  0.9288, -1.6118,  1.4143,  1.2810]])
torch.Size([16]) torch.Size([2, 8])


In [29]:
# To get the value of a size-one tensor with .item()
x = torch.rand(1)
x.item()

0.118507981300354

## Numpy Bridge
In this section, we will convert data between original numpy type to torch.tensor.

*NB The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.*  
<br>

### 1. Converting  a Torch Tensor to a NumPy Array

In [34]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
# they are actually the same thing shared the same memory location, and one cahnges with the other

a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 2. Converting NumPy Array to Torch Tensor

<br> *NB All the Tensors on the CPU except a CharTensor support converting to NumPy and back.*

In [35]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## Cuda Tensors
<br>Tensors can be moved onto any device using the .to method.

In [36]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([1.1185], device='cuda:0')
tensor([1.1185], dtype=torch.float64)
